-- MySQL Script generated by MySQL Workbench
-- Qua 17 Fev 2016 22:54:07 BRST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema questionary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `questionary` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `questionary` ;

-- -----------------------------------------------------
-- Table `questionary`.`admin_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questionary`.`admin_user` (
  `admin_user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`admin_user_id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questionary`.`questionary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questionary`.`questionary` (
  `questionary_id` BIGINT NOT NULL AUTO_INCREMENT,
  `questionary_name` VARCHAR(45) NOT NULL,
  `question_count` INT NOT NULL,
  `created_by_user_id` BIGINT NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`questionary_id`),
  INDEX `fk_questionary_admin_user_idx` (`created_by_user_id` ASC),
  CONSTRAINT `fk_questionary_admin_user`
    FOREIGN KEY (`created_by_user_id`)
    REFERENCES `questionary`.`admin_user` (`admin_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questionary`.`question_score_setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questionary`.`question_score_setting` (
  `question_score_setting_id` BIGINT NOT NULL AUTO_INCREMENT,
  `correct_score` TINYINT NOT NULL DEFAULT 0,
  `wrong_score` TINYINT NOT NULL DEFAULT 0,
  `blank_score` TINYINT NOT NULL DEFAULT 0,
  `creation_date` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`question_score_setting_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questionary`.`question_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questionary`.`question_option` (
  `question_option_id` BIGINT NOT NULL AUTO_INCREMENT,
  `question_option_description` VARCHAR(200) NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`question_option_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questionary`.`question_difficult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questionary`.`question_difficult` (
  `question_difficult_id` BIGINT NOT NULL AUTO_INCREMENT,
  `question_difficult_description` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`question_difficult_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questionary`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questionary`.`question` (
  `question_id` BIGINT NOT NULL AUTO_INCREMENT,
  `question_description` VARCHAR(700) NOT NULL,
  `correct_question_option_id` BIGINT NOT NULL,
  `question_score_setting_id` BIGINT NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT now(),
  `question_difficult_id` BIGINT NOT NULL,
  PRIMARY KEY (`question_id`),
  INDEX `fk_question_question_score_setting1_idx` (`question_score_setting_id` ASC),
  INDEX `fk_question_question_option1_idx` (`correct_question_option_id` ASC),
  INDEX `fk_question_question_difficult1_idx` (`question_difficult_id` ASC),
  CONSTRAINT `fk_question_question_score_setting1`
    FOREIGN KEY (`question_score_setting_id`)
    REFERENCES `questionary`.`question_score_setting` (`question_score_setting_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_question_option1`
    FOREIGN KEY (`correct_question_option_id`)
    REFERENCES `questionary`.`question_option` (`question_option_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_question_difficult1`
    FOREIGN KEY (`question_difficult_id`)
    REFERENCES `questionary`.`question_difficult` (`question_difficult_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questionary`.`question_available_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questionary`.`question_available_option` (
  `question_id` BIGINT NOT NULL,
  `question_option_id` BIGINT NOT NULL,
  PRIMARY KEY (`question_id`, `question_option_id`),
  INDEX `fk_question_has_question_option_question_option1_idx` (`question_option_id` ASC),
  INDEX `fk_question_has_question_option_question1_idx` (`question_id` ASC),
  CONSTRAINT `fk_question_has_question_option_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `questionary`.`question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_has_question_option_question_option1`
    FOREIGN KEY (`question_option_id`)
    REFERENCES `questionary`.`question_option` (`question_option_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questionary`.`questionary_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questionary`.`questionary_question` (
  `questionary_id` BIGINT NOT NULL,
  `question_id` BIGINT NOT NULL,
  PRIMARY KEY (`questionary_id`, `question_id`),
  INDEX `fk_questionary_has_question_question1_idx` (`question_id` ASC),
  INDEX `fk_questionary_has_question_questionary1_idx` (`questionary_id` ASC),
  CONSTRAINT `fk_questionary_has_question_questionary1`
    FOREIGN KEY (`questionary_id`)
    REFERENCES `questionary`.`questionary` (`questionary_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questionary_has_question_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `questionary`.`question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questionary`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questionary`.`user` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `global_execution_limit` INT NOT NULL DEFAULT 0,
  `creation_date` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questionary`.`user_questionary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questionary`.`user_questionary` (
  `user_questionary_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `questionary_id` BIGINT NOT NULL,
  `score` INT NULL,
  `seconds_spent` INT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`user_questionary_id`),
  INDEX `fk_user_has_questionary_questionary1_idx` (`questionary_id` ASC),
  INDEX `fk_user_has_questionary_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_questionary_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `questionary`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_questionary_questionary1`
    FOREIGN KEY (`questionary_id`)
    REFERENCES `questionary`.`questionary` (`questionary_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questionary`.`user_questionary_question_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questionary`.`user_questionary_question_answer` (
  `user_questionary_answer_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_questionary_id` BIGINT NOT NULL,
  `answered_question_option_id` BIGINT NULL,
  `answer_date` DATETIME NULL,
  `creation_date` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`user_questionary_answer_id`),
  INDEX `fk_user_questionary_question_answer_question_option1_idx` (`answered_question_option_id` ASC),
  INDEX `fk_user_questionary_question_answer_user_questionary1_idx` (`user_questionary_id` ASC),
  CONSTRAINT `fk_user_questionary_question_answer_question_option1`
    FOREIGN KEY (`answered_question_option_id`)
    REFERENCES `questionary`.`question_option` (`question_option_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_questionary_question_answer_user_questionary1`
    FOREIGN KEY (`user_questionary_id`)
    REFERENCES `questionary`.`user_questionary` (`user_questionary_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `questionary`.`user_available_questionary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `questionary`.`user_available_questionary` (
  `user_available_questionary_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `questionary_id` BIGINT NOT NULL,
  `execution_limit` INT NOT NULL DEFAULT 0,
  INDEX `fk_user_has_questionary_questionary2_idx` (`questionary_id` ASC),
  INDEX `fk_user_has_questionary_user2_idx` (`user_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `questionary_id_UNIQUE` (`questionary_id` ASC),
  PRIMARY KEY (`user_available_questionary_id`),
  CONSTRAINT `fk_user_has_questionary_user2`
    FOREIGN KEY (`user_id`)
    REFERENCES `questionary`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_questionary_questionary2`
    FOREIGN KEY (`questionary_id`)
    REFERENCES `questionary`.`questionary` (`questionary_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
