
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        AdminUser
* GENERATION DATE:  15.02.2016
* CLASS FILE:       /var/www/html/gen/generated_classes/class.AdminUser.php
* FOR MYSQL TABLE:  admin_user
* FOR MYSQL DB:     mydb
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class AdminUser
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $admin_user_id;   // KEY ATTR. WITH AUTOINCREMENT

var $full_name;   // (normal Attribute)
var $email;   // (normal Attribute)
var $login;   // (normal Attribute)
var $password;   // (normal Attribute)
var $creation_date;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function AdminUser()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getadmin_user_id()
{
return $this->admin_user_id;
}

function getfull_name()
{
return $this->full_name;
}

function getemail()
{
return $this->email;
}

function getlogin()
{
return $this->login;
}

function getpassword()
{
return $this->password;
}

function getcreation_date()
{
return $this->creation_date;
}

// **********************
// SETTER METHODS
// **********************


function setadmin_user_id($val)
{
$this->admin_user_id =  $val;
}

function setfull_name($val)
{
$this->full_name =  $val;
}

function setemail($val)
{
$this->email =  $val;
}

function setlogin($val)
{
$this->login =  $val;
}

function setpassword($val)
{
$this->password =  $val;
}

function setcreation_date($val)
{
$this->creation_date =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM admin_user WHERE admin_user_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->admin_user_id = $row->admin_user_id;

$this->full_name = $row->full_name;

$this->email = $row->email;

$this->login = $row->login;

$this->password = $row->password;

$this->creation_date = $row->creation_date;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM admin_user WHERE admin_user_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->admin_user_id = ""; // clear key for autoincrement

$sql = "INSERT INTO admin_user ( full_name,email,login,password,creation_date ) VALUES ( '$this->full_name','$this->email','$this->login','$this->password','$this->creation_date' )";
$result = $this->database->query($sql);
$this->admin_user_id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE admin_user SET  full_name = '$this->full_name',email = '$this->email',login = '$this->login',password = '$this->password',creation_date = '$this->creation_date' WHERE admin_user_id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
