
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        QuestionaryQuestion
* GENERATION DATE:  15.02.2016
* CLASS FILE:       /var/www/html/gen/generated_classes/class.QuestionaryQuestion.php
* FOR MYSQL TABLE:  questionary_question
* FOR MYSQL DB:     mydb
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class QuestionaryQuestion
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $questionary_question_id;   // KEY ATTR. WITH AUTOINCREMENT

var $questionary_id;   // (normal Attribute)
var $question_id;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function QuestionaryQuestion()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getquestionary_id()
{
return $this->questionary_id;
}

function getquestion_id()
{
return $this->question_id;
}

// **********************
// SETTER METHODS
// **********************


function setquestionary_id($val)
{
$this->questionary_id =  $val;
}

function setquestion_id($val)
{
$this->question_id =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM questionary_question WHERE questionary_question_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->questionary_id = $row->questionary_id;

$this->question_id = $row->question_id;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM questionary_question WHERE questionary_question_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->questionary_question_id = ""; // clear key for autoincrement

$sql = "INSERT INTO questionary_question ( questionary_id,question_id ) VALUES ( '$this->questionary_id','$this->question_id' )";
$result = $this->database->query($sql);
$this->questionary_question_id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE questionary_question SET  questionary_id = '$this->questionary_id',question_id = '$this->question_id' WHERE questionary_question_id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
