
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Question
* GENERATION DATE:  15.02.2016
* CLASS FILE:       /var/www/html/gen/generated_classes/class.Question.php
* FOR MYSQL TABLE:  question
* FOR MYSQL DB:     mydb
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class Question
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $question_id;   // KEY ATTR. WITH AUTOINCREMENT

var $question_description;   // (normal Attribute)
var $seconds_to_answer;   // (normal Attribute)
var $correct_question_option_id;   // (normal Attribute)
var $question_score_setting_id;   // (normal Attribute)
var $creation_date;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function Question()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getquestion_id()
{
return $this->question_id;
}

function getquestion_description()
{
return $this->question_description;
}

function getseconds_to_answer()
{
return $this->seconds_to_answer;
}

function getcorrect_question_option_id()
{
return $this->correct_question_option_id;
}

function getquestion_score_setting_id()
{
return $this->question_score_setting_id;
}

function getcreation_date()
{
return $this->creation_date;
}

// **********************
// SETTER METHODS
// **********************


function setquestion_id($val)
{
$this->question_id =  $val;
}

function setquestion_description($val)
{
$this->question_description =  $val;
}

function setseconds_to_answer($val)
{
$this->seconds_to_answer =  $val;
}

function setcorrect_question_option_id($val)
{
$this->correct_question_option_id =  $val;
}

function setquestion_score_setting_id($val)
{
$this->question_score_setting_id =  $val;
}

function setcreation_date($val)
{
$this->creation_date =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM question WHERE question_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->question_id = $row->question_id;

$this->question_description = $row->question_description;

$this->seconds_to_answer = $row->seconds_to_answer;

$this->correct_question_option_id = $row->correct_question_option_id;

$this->question_score_setting_id = $row->question_score_setting_id;

$this->creation_date = $row->creation_date;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM question WHERE question_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->question_id = ""; // clear key for autoincrement

$sql = "INSERT INTO question ( question_description,seconds_to_answer,correct_question_option_id,question_score_setting_id,creation_date ) VALUES ( '$this->question_description','$this->seconds_to_answer','$this->correct_question_option_id','$this->question_score_setting_id','$this->creation_date' )";
$result = $this->database->query($sql);
$this->question_id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE question SET  question_description = '$this->question_description',seconds_to_answer = '$this->seconds_to_answer',correct_question_option_id = '$this->correct_question_option_id',question_score_setting_id = '$this->question_score_setting_id',creation_date = '$this->creation_date' WHERE question_id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
