
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        QuestionOption
* GENERATION DATE:  15.02.2016
* CLASS FILE:       /var/www/html/gen/generated_classes/class.QuestionOption.php
* FOR MYSQL TABLE:  question_option
* FOR MYSQL DB:     mydb
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class QuestionOption
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $question_option_id;   // KEY ATTR. WITH AUTOINCREMENT

var $question_option_description;   // (normal Attribute)
var $creation_date;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function QuestionOption()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getquestion_option_id()
{
return $this->question_option_id;
}

function getquestion_option_description()
{
return $this->question_option_description;
}

function getcreation_date()
{
return $this->creation_date;
}

// **********************
// SETTER METHODS
// **********************


function setquestion_option_id($val)
{
$this->question_option_id =  $val;
}

function setquestion_option_description($val)
{
$this->question_option_description =  $val;
}

function setcreation_date($val)
{
$this->creation_date =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM question_option WHERE question_option_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->question_option_id = $row->question_option_id;

$this->question_option_description = $row->question_option_description;

$this->creation_date = $row->creation_date;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM question_option WHERE question_option_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->question_option_id = ""; // clear key for autoincrement

$sql = "INSERT INTO question_option ( question_option_description,creation_date ) VALUES ( '$this->question_option_description','$this->creation_date' )";
$result = $this->database->query($sql);
$this->question_option_id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE question_option SET  question_option_description = '$this->question_option_description',creation_date = '$this->creation_date' WHERE question_option_id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
