
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Questionary
* GENERATION DATE:  15.02.2016
* CLASS FILE:       /var/www/html/gen/generated_classes/class.Questionary.php
* FOR MYSQL TABLE:  questionary
* FOR MYSQL DB:     mydb
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class Questionary
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $questionary_id;   // KEY ATTR. WITH AUTOINCREMENT

var $questionary_name;   // (normal Attribute)
var $question_count;   // (normal Attribute)
var $created_by_user_id;   // (normal Attribute)
var $creation_date;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function Questionary()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getquestionary_id()
{
return $this->questionary_id;
}

function getquestionary_name()
{
return $this->questionary_name;
}

function getquestion_count()
{
return $this->question_count;
}

function getcreated_by_user_id()
{
return $this->created_by_user_id;
}

function getcreation_date()
{
return $this->creation_date;
}

// **********************
// SETTER METHODS
// **********************


function setquestionary_id($val)
{
$this->questionary_id =  $val;
}

function setquestionary_name($val)
{
$this->questionary_name =  $val;
}

function setquestion_count($val)
{
$this->question_count =  $val;
}

function setcreated_by_user_id($val)
{
$this->created_by_user_id =  $val;
}

function setcreation_date($val)
{
$this->creation_date =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM questionary WHERE questionary_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->questionary_id = $row->questionary_id;

$this->questionary_name = $row->questionary_name;

$this->question_count = $row->question_count;

$this->created_by_user_id = $row->created_by_user_id;

$this->creation_date = $row->creation_date;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM questionary WHERE questionary_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->questionary_id = ""; // clear key for autoincrement

$sql = "INSERT INTO questionary ( questionary_name,question_count,created_by_user_id,creation_date ) VALUES ( '$this->questionary_name','$this->question_count','$this->created_by_user_id','$this->creation_date' )";
$result = $this->database->query($sql);
$this->questionary_id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE questionary SET  questionary_name = '$this->questionary_name',question_count = '$this->question_count',created_by_user_id = '$this->created_by_user_id',creation_date = '$this->creation_date' WHERE questionary_id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
