
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        UserQuestionaryQuestionAnswer
* GENERATION DATE:  15.02.2016
* CLASS FILE:       /var/www/html/gen/generated_classes/class.UserQuestionaryQuestionAnswer.php
* FOR MYSQL TABLE:  user_questionary_question_answer
* FOR MYSQL DB:     mydb
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class UserQuestionaryQuestionAnswer
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $user_questionary_question_answer_id;   // KEY ATTR. WITH AUTOINCREMENT

var $user_questionary_answer_id;   // (normal Attribute)
var $user_questionary_id;   // (normal Attribute)
var $answered_question_option_id;   // (normal Attribute)
var $answer_date;   // (normal Attribute)
var $creation_date;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function UserQuestionaryQuestionAnswer()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getuser_questionary_answer_id()
{
return $this->user_questionary_answer_id;
}

function getuser_questionary_id()
{
return $this->user_questionary_id;
}

function getanswered_question_option_id()
{
return $this->answered_question_option_id;
}

function getanswer_date()
{
return $this->answer_date;
}

function getcreation_date()
{
return $this->creation_date;
}

// **********************
// SETTER METHODS
// **********************


function setuser_questionary_answer_id($val)
{
$this->user_questionary_answer_id =  $val;
}

function setuser_questionary_id($val)
{
$this->user_questionary_id =  $val;
}

function setanswered_question_option_id($val)
{
$this->answered_question_option_id =  $val;
}

function setanswer_date($val)
{
$this->answer_date =  $val;
}

function setcreation_date($val)
{
$this->creation_date =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM user_questionary_question_answer WHERE user_questionary_question_answer_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->user_questionary_answer_id = $row->user_questionary_answer_id;

$this->user_questionary_id = $row->user_questionary_id;

$this->answered_question_option_id = $row->answered_question_option_id;

$this->answer_date = $row->answer_date;

$this->creation_date = $row->creation_date;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM user_questionary_question_answer WHERE user_questionary_question_answer_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->user_questionary_question_answer_id = ""; // clear key for autoincrement

$sql = "INSERT INTO user_questionary_question_answer ( user_questionary_answer_id,user_questionary_id,answered_question_option_id,answer_date,creation_date ) VALUES ( '$this->user_questionary_answer_id','$this->user_questionary_id','$this->answered_question_option_id','$this->answer_date','$this->creation_date' )";
$result = $this->database->query($sql);
$this->user_questionary_question_answer_id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE user_questionary_question_answer SET  user_questionary_answer_id = '$this->user_questionary_answer_id',user_questionary_id = '$this->user_questionary_id',answered_question_option_id = '$this->answered_question_option_id',answer_date = '$this->answer_date',creation_date = '$this->creation_date' WHERE user_questionary_question_answer_id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
