
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        UserQuestionary
* GENERATION DATE:  15.02.2016
* CLASS FILE:       /var/www/html/gen/generated_classes/class.UserQuestionary.php
* FOR MYSQL TABLE:  user_questionary
* FOR MYSQL DB:     mydb
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class UserQuestionary
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $user_questionary_id;   // KEY ATTR. WITH AUTOINCREMENT

var $user_id;   // (normal Attribute)
var $questionary_id;   // (normal Attribute)
var $score;   // (normal Attribute)
var $creation_date;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function UserQuestionary()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getuser_questionary_id()
{
return $this->user_questionary_id;
}

function getuser_id()
{
return $this->user_id;
}

function getquestionary_id()
{
return $this->questionary_id;
}

function getscore()
{
return $this->score;
}

function getcreation_date()
{
return $this->creation_date;
}

// **********************
// SETTER METHODS
// **********************


function setuser_questionary_id($val)
{
$this->user_questionary_id =  $val;
}

function setuser_id($val)
{
$this->user_id =  $val;
}

function setquestionary_id($val)
{
$this->questionary_id =  $val;
}

function setscore($val)
{
$this->score =  $val;
}

function setcreation_date($val)
{
$this->creation_date =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM user_questionary WHERE user_questionary_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->user_questionary_id = $row->user_questionary_id;

$this->user_id = $row->user_id;

$this->questionary_id = $row->questionary_id;

$this->score = $row->score;

$this->creation_date = $row->creation_date;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM user_questionary WHERE user_questionary_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->user_questionary_id = ""; // clear key for autoincrement

$sql = "INSERT INTO user_questionary ( user_id,questionary_id,score,creation_date ) VALUES ( '$this->user_id','$this->questionary_id','$this->score','$this->creation_date' )";
$result = $this->database->query($sql);
$this->user_questionary_id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE user_questionary SET  user_id = '$this->user_id',questionary_id = '$this->questionary_id',score = '$this->score',creation_date = '$this->creation_date' WHERE user_questionary_id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
