
<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        User
* GENERATION DATE:  15.02.2016
* CLASS FILE:       /var/www/html/gen/generated_classes/class.User.php
* FOR MYSQL TABLE:  user
* FOR MYSQL DB:     mydb
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class User
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $user_id;   // KEY ATTR. WITH AUTOINCREMENT

var $full_name;   // (normal Attribute)
var $email;   // (normal Attribute)
var $login;   // (normal Attribute)
var $password;   // (normal Attribute)
var $active;   // (normal Attribute)
var $creation_date;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function User()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getuser_id()
{
return $this->user_id;
}

function getfull_name()
{
return $this->full_name;
}

function getemail()
{
return $this->email;
}

function getlogin()
{
return $this->login;
}

function getpassword()
{
return $this->password;
}

function getactive()
{
return $this->active;
}

function getcreation_date()
{
return $this->creation_date;
}

// **********************
// SETTER METHODS
// **********************


function setuser_id($val)
{
$this->user_id =  $val;
}

function setfull_name($val)
{
$this->full_name =  $val;
}

function setemail($val)
{
$this->email =  $val;
}

function setlogin($val)
{
$this->login =  $val;
}

function setpassword($val)
{
$this->password =  $val;
}

function setactive($val)
{
$this->active =  $val;
}

function setcreation_date($val)
{
$this->creation_date =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM user WHERE user_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->user_id = $row->user_id;

$this->full_name = $row->full_name;

$this->email = $row->email;

$this->login = $row->login;

$this->password = $row->password;

$this->active = $row->active;

$this->creation_date = $row->creation_date;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM user WHERE user_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->user_id = ""; // clear key for autoincrement

$sql = "INSERT INTO user ( full_name,email,login,password,active,creation_date ) VALUES ( '$this->full_name','$this->email','$this->login','$this->password','$this->active','$this->creation_date' )";
$result = $this->database->query($sql);
$this->user_id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE user SET  full_name = '$this->full_name',email = '$this->email',login = '$this->login',password = '$this->password',active = '$this->active',creation_date = '$this->creation_date' WHERE user_id = $id ";

$result = $this->database->query($sql);



}


} // class : end

?>
<!-- end of generated class -->
